name: cloud-native app 

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  TAG: 3.20.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #  Checkout Karavan
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: karavan

      #  Checkout Infinispan Quarkus Embedded 
        uses: actions/checkout@v3
        with:
          repository: infinispan/infinispan-quarkus
          path: infinispan
          ref: 14.0.5.Final

      #  Generate Karavan UI model and API, Kamelets and Components
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/camel/karavan
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      #  Build Karavan cloud app with public access
      
      - name: Build Infinispan Quarkus Embedded 
        run: |
          mvn install -f infinispan -N \
          && mvn install -f infinispan/embedded -DskipTests

      #  Generate Karavan    
      - name: Generate Karavan UI model and API, Kamelets and Components
        run: |
          mvn clean compile exec:java -f karavan/karavan-generator \
          -Dexec.mainClass="org.apache.camel.karavan.generator.KaravanGenerator"

      #  Building Karavan Core
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Karavan Core install
        working-directory: ./karavan/karavan-core
        run: npm ci

      #  Build Karavan cloud app with public access
      - name: Build application public
        run: |
          mvn package -f karavan/karavan-app -Dquarkus.profile=public -DskipTest \
          -Dquarkus.quinoa.package-manager-install=false \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.image=ghcr.io/${GITHUB_REPOSITORY}:${{ env.TAG }} \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}

      #  Build Karavan cloud app with basic authorization
      - name: Build application basic auth
        run: |
          mvn package -f karavan/karavan-app -Dquarkus.profile=basic -DskipTest \
          -Dquarkus.quinoa.package-manager-install=false \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.image=ghcr.io/${GITHUB_REPOSITORY}-basic:${{ env.TAG }} \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}

      #  Build Karavan cloud app with oidc authorization
      - name: Build application oidc
        run: |
          mvn package -f karavan/karavan-app -Dquarkus.profile=oidc -DskipTest \
          -Dquarkus.quinoa.package-manager-install=false \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.image=ghcr.io/${GITHUB_REPOSITORY}-oidc:${{ env.TAG }} \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}
