name: operator 

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths: ['karavan-operator/**']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-operator
  IMAGE_NAME_BUNDLE: ${{ github.repository }}-bundle
  TAG: 3.20.2-SNAPSHOT

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #  Generate Karavan UI model and API, Kamelets and Components
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/camel/karavan
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v2
        with:
          version: v0.17.0
          node_image: "kindest/node:v1.24.7"
          registry: false

      - name: Test operator
        run: |
          mvn test -f karavan-operator -Pintegration-tests

      - name: Test operator (end-to-end)
        run: |
          cd karavan-operator
          make test-deploy-kind
          mvn test -Pend-to-end-tests
          make test-undeploy-kind

      #  Build Karavan operator
      - name: Build operator
        run: |
          mvn package -f karavan-operator -DskipTest \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}

      #  Build the Operator Bundle image
      - name: Build operator Bundle image
        run: |
          cd karavan-operator
          MY_BUNDLE_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BUNDLE }}:${{ env.TAG }}
          docker login -u=${{ github.actor }} -p=${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
          docker build -t $MY_BUNDLE_IMAGE -f target/bundle/camel-karavan-operator.v${{env.TAG}}/bundle.Dockerfile target/bundle/camel-karavan-operator.v${{ env.TAG }}
          docker push $MY_BUNDLE_IMAGE
        if: ${{ github.ref == 'refs/heads/main' }}