apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: "karavan"
  app.kubernetes.io/part-of: "karavan"
  app.kubernetes.io/name: "karavan"
  app.kubernetes.io/version: "4.8.0"
namespace: "karavan"
resources:
  - secret.yaml
  - role.yaml
  - service-account.yaml
  - role-binding.yaml
  - deployment.yaml
  - service.yaml

# Patch for Service with nodePort
patches:
  - path: ./nodePort.yaml
    target:
      kind: "Service"
      name: "karavan"
      
# Replace secret from.env if required
secretGenerator:
- name: karavan
  behavior: replace
  options:
      disableNameSuffixHash: true
  envs:
    - .env